# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
# Checkout the code
- task: Checkout@1
  inputs:
    clean: true
    fetchDepth: 0

# Build and test the Java project with Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'  # Ensure that Java 11 is available
    jdkArchitectureOption: 'x64'  # Use x64 architecture
    mavenOptions: '-Xmx3072m'  # Optional: increase memory for Maven
    publishJUnitResults: true  # Optional: publish JUnit test results
    testResultsFiles: '**/surefire-reports/TEST-*.xml'  # Optional: path to test results
